CREATE TABLE TB_CAREER_JOB (
    JOBDIC_SEQ       VARCHAR2(20)   PRIMARY KEY,
    JOB              VARCHAR2(200)  NOT NULL,
    APTD_TYPE_CODE   VARCHAR2(50),
    PROFESSION       VARCHAR2(100),
    INDUSTRY_CD      VARCHAR2(10)   NOT NULL,
    CERTIFICATION    CLOB,
    TRAINING         CLOB,
    PREPARATION      CLOB
);
